[link](https://machinelearningmastery.com/calculate-principal-component-analysis-scratch-python/)

In [30]:
from numpy import array
from numpy import mean
from numpy import std
from numpy import cov
from numpy.linalg import eig
from numpy.linalg import svd


In [26]:
# define a matrix
A = array([[1, 2,4], [3, 4,3], [5, 6,5],[6,7,6], [5,9,7]])
print(A)


[[1 2 4]
 [3 4 3]
 [5 6 5]
 [6 7 6]
 [5 9 7]]


In [27]:
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)


[4.  5.6 5. ]


In [28]:
# center columns by subtracting column means
C = A - M
print(C)


[[-3.  -3.6 -1. ]
 [-1.  -1.6 -2. ]
 [ 1.   0.4  0. ]
 [ 2.   1.4  1. ]
 [ 1.   3.4  2. ]]


In [31]:
st = std(A.T, axis = 1)
st

array([1.78885438, 2.41660919, 1.41421356])

In [33]:
scale = C / st
scale

array([[-1.67705098, -1.4896906 , -0.70710678],
       [-0.55901699, -0.66208471, -1.41421356],
       [ 0.55901699,  0.16552118,  0.        ],
       [ 1.11803399,  0.57932412,  0.70710678],
       [ 0.55901699,  1.40693001,  1.41421356]])

In [29]:
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)


[[4.   4.75 2.25]
 [4.75 7.3  3.75]
 [2.25 3.75 2.5 ]]


In [15]:
# eigendecomposition of covariance matrix
values, vectors = eig(V)



In [16]:
print(vectors)

[[-0.52253251 -0.74622452  0.41244241]
 [-0.75419632  0.17891219 -0.63180562]
 [-0.39767787  0.64120153  0.65628721]]


In [17]:
print(values)

[12.56828543  0.92781962  0.30389496]


In [14]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[ 4.68038215  0.95338815  0.38088579]
 [ 2.52460236 -0.82243804 -0.71412784]
 [-0.82421104 -0.67465964  0.15972016]
 [-2.49861774 -0.60077044  0.59664417]
 [-3.88215573  1.14447997 -0.42312228]]


In [24]:
# by svd

In [20]:
  U, S, V = svd(V)

In [21]:
#vector
U

array([[-0.52253251,  0.74622452,  0.41244241],
       [-0.75419632, -0.17891219, -0.63180562],
       [-0.39767787, -0.64120153,  0.65628721]])

In [22]:
#values
S

array([12.56828543,  0.92781962,  0.30389496])

In [23]:
V

array([[-0.52253251, -0.75419632, -0.39767787],
       [ 0.74622452, -0.17891219, -0.64120153],
       [ 0.41244241, -0.63180562,  0.65628721]])